-- AlterTable
ALTER TABLE "Planet" ALTER COLUMN "semimajor_axis" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mass" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Satellite" ALTER COLUMN "semimajor_axis" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "mass" SET DATA TYPE DOUBLE PRECISION;
